### ISSUE TITLE
Plugin blocks Mappings that include double quote character (")

### ISSUE THREAD

**Issue by reckoner** [junegunn/vim-peekaboo#8]
Hi,

I love your plugin, but my mappings such as 

    nmap <M-o> "+gP
    imap <M-o> <ESC>"+gP

No longer work because  your plug-in changes the double quote character. Is there a way around this?

Thanks!

**Comment by junegunn** [comment]
I don't understand why they don't work. They should still work though you may find pointless flashing of the peekaboo window annoying. It's possible that the other key bindings in your config are getting in the way. 

Having said that, it is strongly recommended and considered to be a good practice that you *always* use `noremap`s instead of `map`s unless you explicitly want recursive expansion of the keys.

```vim
nnoremap <M-o> "+gP
inoremap <M-o> <ESC>"+gP
```

With noremaps, `"` is translated as it is, and peekaboo will not be invoked.
